name: Testing workflow variables
on:
  workflow dispatch
env:
  cloud: AWS
jobs:
  greeting Job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      steps:
        - name: "Say Hello Mona it's Monday"
          run: echo "sGreeting SFirst Name is using Scloud!"
          env:
            First Name: Praveen
